name: secure_pgp_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=3.10.0 <4.0.0' # Use this standard range format

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  openpgp: ^3.10.6
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: ture
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#263238"
  adaptive_icon_foreground: "assets/icon/app_icon.png"